In [1]:
# import libraries
import pandas as pd

# load csvs as dfs
df_bcpi = pd.read_csv("/Users/abijeetdhillon/MDSA/DATA604/data604_project/data/raw/BCPI_MONTHLY-sd-1972-01-01.csv")
df_ceer = pd.read_csv("/Users/abijeetdhillon/MDSA/DATA604/data604_project/data/raw/CEER_BROADM,CEER_MCM,CEER_OITPM,CEER_BROAD_XUSM-sd-1990-01-01.csv")

In [7]:
# check if duplicates
duplicates_bcpi = df_bcpi[df_bcpi['date'].duplicated()]
duplicated_ceer = df_ceer[df_ceer['date'].duplicated()]
print(len(duplicates_bcpi))
print(len(duplicated_ceer))

# convert date string column to date datetime column type
df_bcpi['date'] = pd.to_datetime(df_bcpi['date'])
df_ceer['date'] = pd.to_datetime(df_ceer['date'])

# change datetime format to yyyy-mm
df_bcpi['date'] = pd.to_datetime(df_bcpi['date']).dt.strftime("%Y-%m")
df_ceer['date'] = pd.to_datetime(df_ceer['date']).dt.strftime("%Y-%m")

# make both dataframes only have data from jan 2015 to dec 2025
df_bcpi = df_bcpi.loc[(df_bcpi['date'] >= "2015-01") & (df_bcpi['date'] <= '2025-12')]
df_ceer = df_ceer.loc[(df_ceer['date'] >= "2015-01") & (df_ceer['date'] <= '2025-12')]
display(df_bcpi)
display(df_ceer)

0
0

        date  M.BCPI  M.BCNE   M.ENER   M.MTLS  M.FOPR  M.AGRI   M.FISH
516  2015-01  398.30  346.98   829.23   544.85  360.47  266.75  1300.57
517  2015-02  407.23  340.20   887.09   539.79  351.96  259.38  1251.90
518  2015-03  393.01  336.46   833.92   530.60  333.70  263.56  1317.27
519  2015-04  417.16  335.18   948.59   538.60  318.66  260.51  1503.55
520  2015-05  443.03  338.67  1062.41   546.57  315.33  267.03  1404.91
..       ...     ...     ...      ...      ...     ...     ...      ...
643  2025-08  601.47  518.20  1175.97   948.11  489.79  338.80  1748.73
644  2025-09  605.45  520.82  1185.45   989.14  463.59  332.63  1782.87
645  2025-10  602.66  533.45  1148.28  1045.25  471.39  327.97  1908.21
646  2025-11  609.84  528.13  1186.32  1053.69  441.11  324.85  1863.63
647  2025-12  604.64  538.84  1144.47  1092.69  442.43  327.90  1823.66

[132 rows x 8 columns]

        date  CEER_BROADM  CEER_BROAD_XUSM  CEER_MCM  CEER_OITPM
192  2015-01       112.83           108.73    119.65       96.17
193  2015-02       110.52           107.15    117.03       94.53
194  2015-03       111.04           109.01    117.24       95.61
195  2015-04       113.05           110.74    119.50       97.10
196  2015-05       114.35           111.91    120.33       99.27
..       ...          ...              ...       ...         ...
319  2025-08       105.21           111.68    104.68      103.58
320  2025-09       104.44           110.56    104.10      102.43
321  2025-10       103.73           109.88    103.52      101.46
322  2025-11       103.61           109.97    103.57      100.98
323  2025-12       104.68           110.53    104.83      101.60

[132 rows x 5 columns]

In [8]:
# create combined dataset
df_combined = df_bcpi.merge(df_ceer, on = "date", how = "outer")
df_combined['geography'] = "Canada"
display(df_combined)

,date,M.BCPI,M.BCNE,M.ENER,M.MTLS,M.FOPR,M.AGRI,M.FISH,CEER_BROADM,CEER_BROAD_XUSM,CEER_MCM,CEER_OITPM,geography
0,2015-01,398.30,346.98,829.23,544.85,360.47,266.75,1300.57,112.83,108.73,119.65,96.17,Canada
1,2015-02,407.23,340.20,887.09,539.79,351.96,259.38,1251.90,110.52,107.15,117.03,94.53,Canada
2,2015-03,393.01,336.46,833.92,530.60,333.70,263.56,1317.27,111.04,109.01,117.24,95.61,Canada
3,2015-04,417.16,335.18,948.59,538.60,318.66,260.51,1503.55,113.05,110.74,119.50,97.10,Canada
4,2015-05,443.03,338.67,1062.41,546.57,315.33,267.03,1404.91,114.35,111.91,120.33,99.27,Canada
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,2025-08,601.47,518.20,1175.97,948.11,489.79,338.80,1748.73,105.21,111.68,104.68,103.58,Canada
128,2025-09,605.45,520.82,1185.45,989.14,463.59,332.63,1782.87,104.44,110.56,104.10,102.43,Canada
129,2025-10,602.66,533.45,1148.28,1045.25,471.39,327.97,1908.21,103.73,109.88,103.52,101.46,Canada
130,2025-11,609.84,528.13,1186.32,1053.69,441.11,324.85,1863.63,103.61,109.97,103.57,100.98,Canada
131,2025-12,604.64,538.84,1144.47,1092.69,442.43,327.90,1823.66,104.68,110.53,104.83,101.60,Canada

In [4]:
# save combined dataset to /data/processed
from pathlib import Path
import os

combined_dir_path = Path("../data/processed/")
combined_dir_path.mkdir(parents=True, exist_ok=True)

combined_file_path = combined_dir_path / "df_combined.csv"
df_combined.to_csv(combined_file_path)

In [5]:
df_combined

,date,M.BCPI,M.BCNE,M.ENER,M.MTLS,M.FOPR,M.AGRI,M.FISH,CEER_BROADM,CEER_BROAD_XUSM,CEER_MCM,CEER_OITPM,geography
0,2015-01-01,398.30,346.98,829.23,544.85,360.47,266.75,1300.57,112.83,108.73,119.65,96.17,Canada
1,2015-02-01,407.23,340.20,887.09,539.79,351.96,259.38,1251.90,110.52,107.15,117.03,94.53,Canada
2,2015-03-01,393.01,336.46,833.92,530.60,333.70,263.56,1317.27,111.04,109.01,117.24,95.61,Canada
3,2015-04-01,417.16,335.18,948.59,538.60,318.66,260.51,1503.55,113.05,110.74,119.50,97.10,Canada
4,2015-05-01,443.03,338.67,1062.41,546.57,315.33,267.03,1404.91,114.35,111.91,120.33,99.27,Canada
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,2025-08-01,601.47,518.20,1175.97,948.11,489.79,338.80,1748.73,105.21,111.68,104.68,103.58,Canada
128,2025-09-01,605.45,520.82,1185.45,989.14,463.59,332.63,1782.87,104.44,110.56,104.10,102.43,Canada
129,2025-10-01,602.66,533.45,1148.28,1045.25,471.39,327.97,1908.21,103.73,109.88,103.52,101.46,Canada
130,2025-11-01,609.84,528.13,1186.32,1053.69,441.11,324.85,1863.63,103.61,109.97,103.57,100.98,Canada
131,2025-12-01,604.64,538.84,1144.47,1092.69,442.43,327.90,1823.66,104.68,110.53,104.83,101.60,Canada