In [1]:
# import libraries
import pandas as pd

# load csvs as dfs
df_bcpi = pd.read_csv("/Users/abijeetdhillon/MDSA/DATA604/data604_project/data/raw/BCPI_MONTHLY-sd-1972-01-01.csv")
df_ceer = pd.read_csv("/Users/abijeetdhillon/MDSA/DATA604/data604_project/data/raw/CEER_BROADM,CEER_MCM,CEER_OITPM,CEER_BROAD_XUSM-sd-1990-01-01.csv")

In [2]:
# check if duplicates
duplicates_bcpi = df_bcpi[df_bcpi['date'].duplicated()]
duplicated_ceer = df_ceer[df_ceer['date'].duplicated()]
print(len(duplicates_bcpi))
print(len(duplicated_ceer))

# convert date string column to date datetime column type
df_bcpi['date'] = pd.to_datetime(df_bcpi['date'])
df_ceer['date'] = pd.to_datetime(df_ceer['date'])

# make date index
df_bcpi = df_bcpi.set_index('date')
df_ceer = df_ceer.set_index('date')

# change datetime index format to yyyy-mm
df_bcpi.index = df_bcpi.index.strftime("%Y-%m")
df_ceer.index = df_ceer.index.strftime("%Y-%m")

# make both dataframes only have data from jan 2015 to dec 2025
df_bcpi = df_bcpi.loc["2015-01":"2025-12"]
df_ceer = df_ceer.loc["2015-01":"2025-12"]
display(df_bcpi)
display(df_ceer)

0
0

         M.BCPI  M.BCNE   M.ENER   M.MTLS  M.FOPR  M.AGRI   M.FISH
date
2015-01  398.30  346.98   829.23   544.85  360.47  266.75  1300.57
2015-02  407.23  340.20   887.09   539.79  351.96  259.38  1251.90
2015-03  393.01  336.46   833.92   530.60  333.70  263.56  1317.27
2015-04  417.16  335.18   948.59   538.60  318.66  260.51  1503.55
2015-05  443.03  338.67  1062.41   546.57  315.33  267.03  1404.91
...         ...     ...      ...      ...     ...     ...      ...
2025-08  601.47  518.20  1175.97   948.11  489.79  338.80  1748.73
2025-09  605.45  520.82  1185.45   989.14  463.59  332.63  1782.87
2025-10  602.66  533.45  1148.28  1045.25  471.39  327.97  1908.21
2025-11  609.84  528.13  1186.32  1053.69  441.11  324.85  1863.63
2025-12  604.64  538.84  1144.47  1092.69  442.43  327.90  1823.66

[132 rows x 7 columns]

         CEER_BROADM  CEER_BROAD_XUSM  CEER_MCM  CEER_OITPM
date
2015-01       112.83           108.73    119.65       96.17
2015-02       110.52           107.15    117.03       94.53
2015-03       111.04           109.01    117.24       95.61
2015-04       113.05           110.74    119.50       97.10
2015-05       114.35           111.91    120.33       99.27
...              ...              ...       ...         ...
2025-08       105.21           111.68    104.68      103.58
2025-09       104.44           110.56    104.10      102.43
2025-10       103.73           109.88    103.52      101.46
2025-11       103.61           109.97    103.57      100.98
2025-12       104.68           110.53    104.83      101.60

[132 rows x 4 columns]

In [ ]:
# create combined dataset
df_combined = df_bcpi.join(df_ceer, how = "outer")
display(df_combined)

,M.BCPI,M.BCNE,M.ENER,M.MTLS,M.FOPR,M.AGRI,M.FISH,CEER_BROADM,CEER_BROAD_XUSM,CEER_MCM,CEER_OITPM
date,,,,,,,,,,,
2015-01,398.30,346.98,829.23,544.85,360.47,266.75,1300.57,112.83,108.73,119.65,96.17
2015-02,407.23,340.20,887.09,539.79,351.96,259.38,1251.90,110.52,107.15,117.03,94.53
2015-03,393.01,336.46,833.92,530.60,333.70,263.56,1317.27,111.04,109.01,117.24,95.61
2015-04,417.16,335.18,948.59,538.60,318.66,260.51,1503.55,113.05,110.74,119.50,97.10
2015-05,443.03,338.67,1062.41,546.57,315.33,267.03,1404.91,114.35,111.91,120.33,99.27
...,...,...,...,...,...,...,...,...,...,...,...
2025-08,601.47,518.20,1175.97,948.11,489.79,338.80,1748.73,105.21,111.68,104.68,103.58
2025-09,605.45,520.82,1185.45,989.14,463.59,332.63,1782.87,104.44,110.56,104.10,102.43
2025-10,602.66,533.45,1148.28,1045.25,471.39,327.97,1908.21,103.73,109.88,103.52,101.46
2025-11,609.84,528.13,1186.32,1053.69,441.11,324.85,1863.63,103.61,109.97,103.57,100.98
2025-12,604.64,538.84,1144.47,1092.69,442.43,327.90,1823.66,104.68,110.53,104.83,101.60

In [7]:
# save combined dataset to /data/processed
from pathlib import Path
import os

combined_dir_path = Path("../data/processed/")
combined_dir_path.mkdir(parents=True, exist_ok=True)

combined_file_path = combined_dir_path / "df_combined.csv"
df_combined.to_csv(combined_file_path)